#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-next-image-demo"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
